name: 🤖 AI Agent Task
about: Завдання для AI-агента
title: '[AGENT] '
labels: ['ai-agent-task']
assignees: ''

---

## 🎯 Контекст Завдання

**Агент:** <!-- Вкажи агента: copilot, claude, codex, gemini -->
**Пріоритет:** <!-- high, medium, low -->
**Очікуваний час:** <!-- в годинах -->
**Залежності:** <!-- Issues які мають бути завершені спочатку -->

## 📋 Опис Завдання

<!-- Детально опиши що потрібно зробити -->

## 🎯 Очікуваний Результат

<!-- Що має бути створено/змінено -->

## ✅ Критерії Успіху

- [ ] Код компілюється без помилок
- [ ] Тести проходять успішно
- [ ] Документація оновлена
- [ ] Code review пройшов
- [ ] PR мержений

## 🔍 Спосіб Верифікації

<!-- Як перевірити що завдання виконано -->

## 📚 Джерела

<!-- Посилання на документацію, приклади, контракти -->

- [ ] `docs/INTERFACE_CONTRACTS.md`
- [ ] `docs/IMPLEMENTATION_EXAMPLES.md`
- [ ] `docs/architecture.md`
- [ ] Інші: <!-- вкажи -->

## 🚨 Межі Дозволів

**Що МОЖНА робити:**
<!-- Вкажи що агент може змінювати -->

**Що НЕ МОЖНА робити:**
<!-- Вкажи що агент не може змінювати -->

## 📊 Прогрес

<!-- Агент буде оновлювати цей розділ -->

### Статус: 🟡 In Progress

**Що зроблено:**
-

**Що в роботі:**
-

**Наступні кроки:**
-

**ETA:**

## 🔗 Пов'язані Issues

<!-- Посилання на пов'язані Issues -->

## 📝 Нотатки

<!-- Додаткові нотатки -->
